import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { lora } from "./fonts";
import { FontProvider } from "./FontContext";

export const metadata: Metadata = {
  title: "Dictionary Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${lora.className}`}>
        <ThemeProvider attribute="class">
          <FontProvider>{children}</FontProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
