import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { lora } from "./fonts";
import { FontProvider } from "./FontContext";
import AxeInitializer from "./AxeInitializer";

export const metadata: Metadata = {
  title: "Dictionary Web App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${lora.className}`}>
        <ThemeProvider attribute="class">
          <FontProvider>
            {/* <AxeInitializer /> */}
            {children}
          </FontProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;
